lugares = ['Ilha Bela','Bonito - MS','Fernando de Noronha','Grécia','Irlanda']
print (sorted(lugares))
print (lugares)
print(sorted(lugares, reverse=True))
lugares.reverse()
print (lugares)
lugares.reverse()
print (lugares)
lugares.sort()
print (lugares)
lugares.sort(reverse=True)
print (lugares)